# Generated by Django 5.0.7 on 2024-07-12 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photolog', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pk']},
        ),
    ]
